{% set version = "5.3.6" %}

package:
  name: lua53
  version: {{ version }}
source:
  - url: https://www.lua.org/ftp/lua-{{ version }}.tar.gz
    sha256: fc5fd69bb8736323f026672b1b7235da613d7177e72558893a0bdcd320466d60
    patches:
      # Build as a shared library
      - liblua.so.patch
  - path: CMakeLists.txt

build:
  number: 1
  skip: true  # [not linux]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - sed
    - make
    - coreutils
  host:
    - readline
    - ncurses
  run:
    - readline
    - ncurses

test:
  commands:
    - test -f $PREFIX/lib/liblua5.3.so
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: doc/readme.html

extra:
  recipe-maintainers:
    - alexbw
    - seanyen
    - izahn
