{% set version = "5.1.5" %}

package:
  name: lua
  version: {{ version }}

source:
  - url: https://www.lua.org/ftp/lua-{{ version }}.tar.gz
    sha256: 2640fc56a795f29d28ef15e13c34a47e223960b0240e8cb0a82d9b0738695333
    patches:
      # add proper readline support, as well as proper paths for package loading
      - update.patch  # [not win]

build:
  number: 3
  detect_binary_files_with_prefix: true
  skip: True  # [win]
  run_exports:
    # http://www.lua.org/versions.html#numbering
    - {{ pin_subpackage('lua', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - readline
    - ncurses
  run:
    - readline
    - ncurses

test:
  commands:
    - test -f $PREFIX/lib/liblua$SHLIB_EXT
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - alexbw
    - seanyen
    - izahn
